import numpy as np
import pandas as pd
import os
import sys
from .Blade import Blade
from .APC_Reader import APC_Reader
from .Hub import Hub
from .Propeller import Propeller
#from ocp_vscode import show_object
from datetime import datetime
import cadquery as cq
import matplotlib
matplotlib.use('TkAgg') # Needed to show plots in a separate window
import matplotlib.pyplot as plt


def generateSTL(PE0_NAME, MAIN_DIRECTORY, TARGET_STL_DIRECTORY, INTERPOLATION_POINTS):


    # Get the absolute path of the current script
    #script_path = os.path.abspath(sys.argv[0])
        
    # Get the directory name from that path
    #script_dir = os.path.dirname(script_path)
        
    # Change the current working directory
    #os.chdir(script_dir)

    hub_geometry_types = { ## valid for 9-11" propellers #todo find parameterization for different diameters
                    "-PERF": [1/2, 0, 0.5],
                    "E-PERF": [0.8/2, 0, 0.4],
                    "MR-PERF": [0.65/2, 0, 0.35],
                    "WE-PERF": [0.8/2, 0, 0.41],
                    "SF-PERF": [0.5/2, 0, 0.3],
                    "EP-PERF": [0.8/2, 0, 0.38],
                    "C-PERF": [1/2, 0, 0.56],
                    }

    interpolation_points = INTERPOLATION_POINTS ## Number of Points to define each, the lower and upper side of the airfoil. Total number of points per airfoil is 2*interpolation_points
    ### this markably impacts filesize and to an extend processing speed. Quality (especially around leading edge) decreases at around 20 points
    ### Lofts are automatically splining to points, so the general shape is preserved even with fewer points, however then the shape begins to deviate from the with more points. If super low filesize is crucial, this can be reduced to 5-10 points
    counterclockwise_rotation = True  ## if false, propeller is mirrored
    linear_interpolation = False  ## Set to true for testing and faster processing. Products are not linearly interpolated
    rotation_axis_is_Y = True ## Default Axis of rotation is around Z. If true, propeller is rotated such that axis of rotation is around Y
    ########################################################################################################################
    # READ ME
    # This script generates a propeller.step from an APC propeller geometry file as found here: https://www.apcprop.com/technical-information/file-downloads/.
    # The propeller is generated in 3 parts: Hub, Blade and Propeller.
    # (Visualization via ocp_Viewer (Visual Studio Code only) or CQ-Editor)
    # The hub geometry is generated based on the propeller name. The hub geometry can also be defined manually if inferred incorrectly.
    # The blade is generated based on the APC propeller geometry file. Supported airfoil types are NACA, E63 and CLARK-Y.
    # The transition part between the hub and the blade is a loft (splined) between the first 2 airfoils and 2 ellipses at the hub center.
    # The propeller is generated by combining the hub, blade and transition part.
    # The propeller is exported as a .step (and .stl file in the "Generated Propeller Exports" folder).

    # Usage instructions:
    # Select the APC propeller geometry file and change the filename variable to the path of the file.
    # Set the hub geometry type to the propeller name or define the hub geometry manually.
    # Run the script.
    # ########################################################################################################################
    
    pe0_directory_path = os.path.join(MAIN_DIRECTORY, "PropGeom", "APC Propeller Geometry Data")

    file_string = PE0_NAME + ".PE0" 

    pe0_file_path = os.path.join(pe0_directory_path, file_string)

    print(pe0_file_path)

    
    ### CHANGE FILENAME HERE
    filename = pe0_file_path
    ### SET HUB GEOMETRY HERE (or leave as is to infer from propeller name)
    infer_hub_geometry = True  # If true, hub geometry is inferred from the propeller name and overwrites the following values. If False, hub geometry has to be defined manually below
    outer_radius = 0.8 / 2  # Hub Diameter [in] / 2
    inner_radius = 0  # Shaft Diameter [in] / 2
    thickness = 0.4  # Hub Thickness [in]
    ########################################################################################################################

    propeller_name = os.path.basename(filename).split(".")[0]
    hubtype = ''.join([i for i in propeller_name.upper().split("X")[1] if not i.isdigit()])
    #propeller_name = propeller_name + f"_IP{interpolation_points}"

    ### Create Hub
    if infer_hub_geometry:
        outer_radius, inner_radius, thickness = hub_geometry_types[hubtype]
    hub = Hub(interpolation_points*2-1, outer_radius, inner_radius, thickness)
    hub.create_hub_outline()
    #show_object(hub.part)
    print("### Hub created ###")

    apcreader = APC_Reader(filename)
    # Thickness Variation (for thermal issues):
    max_mm = 0.00  #[mm] (outer radius)
    min_mm = 0.00  #[mm] (at innermost airfoil)
    thickness_variation_blade1 = np.linspace(max_mm, min_mm, num=len(apcreader.thickness_ratio))
    thickness_variation_blade2 = - thickness_variation_blade1  # +/-

    ### Create Blade
    # section_adaptation = np.array([0.4, 1, 1.75, 0.9])  # to account for Cross-sectional Area differences between APC and generated propeller
    section_adaptation = None
    # E63_correction = 0.88
    E63_correction = 1
    blade = Blade(apcreader, hub, interpolation_points, linear_interpolation=linear_interpolation,
                thickness_variation=thickness_variation_blade1, section_adaptation=section_adaptation, E63_correction=E63_correction)
    s = blade.create_blade(export=False)
    #show_object(s)

    ### Create Blade2
    if max_mm == 0 and min_mm == 0:
        blade2 = blade
    else:
        blade2 = Blade(apcreader, hub, interpolation_points, linear_interpolation=linear_interpolation,
                    thickness_variation=thickness_variation_blade2, section_adaptation=section_adaptation)
        s2 = blade2.create_blade(export=False)
        #show_object(s2)

        #calculate volume of propeller
        v1 = blade.blade_solid.val().Volume()
        v2 = blade2.blade_solid.val().Volume()
        print(v1, v2, v1/v2)

    ### Create Propeller
    propeller = Propeller(blade.blade_solid, hub, Blade2=blade2.blade_solid, linear_interpolation=linear_interpolation,
                        ccw=counterclockwise_rotation, attachment_points=False)

    propeller.cleanup()

    if isinstance(propeller.part, cq.Workplane):
        propeller.part.objects[0] = propeller.part.objects[0].scale(0.0254)  # Convert from inches to m
    else:
        propeller.part = propeller.part.scale(0.0254)

    if rotation_axis_is_Y:
        propeller.part = propeller.part.rotate((0,0,0), (1,0,0), 90)


    #propeller.part.objects[0].exportStep(os.getcwd() + f"\\Generated Propeller Exports\\{propeller_name}.step")
    # propeller.part.val().exportStep(f"{propeller_name}_val.step", precision_mode=1, write_pcurves=False)
    # # cq.exporters.export(propeller.part.objects[0], f"{propeller_name}_cq_export.step", opt={'precision_mode': 2, 'write_pcurves': False})

    export_folder = TARGET_STL_DIRECTORY

    if not os.path.exists(export_folder):
        os.makedirs(export_folder)
    
    export_path = os.path.join(export_folder, "propellerTip.stl")

    propeller.part.objects[0].exportStl(export_path) #, precision_mode=-1, write_pcurves=False)

    print("### Propeller STL exported ###")



    # propeller.part = propeller.part.rotate((0,0,0), (1,0,0), 1)
    #show_object(propeller.part) # requires ocp_Viewer (Visual Studio Code only)
    #
    # from sklearn.cluster import DBSCAN
    # ## compare with point cloud
    # df = pd.read_csv(r"C:\Users\RhinerLenny\OneDrive - inspire AG\BAZL\airfoil_data\Point Clouds Rhysearch\Punktewolke_10x7E_LI_oben.asc", delim_whitespace=True, header=None, names=['x', 'y', 'z'])
    # df = df.drop_duplicates(subset=['x', 'y', 'z'])
    #
    # epsilon = 1  # Adjust this value as needed
    # dbscan = DBSCAN(eps=epsilon, min_samples=1)
    # df['line_group'] = dbscan.fit_predict(df[['x']])
    # lines = df.groupby('line_group')
    # print(len(lines))
    #
    # splines = []
    # llines = []
    # for num, (_, line) in enumerate(lines):
    #     # if num == 0:
    #     print(num, end="\r")
    #     lline = line[['x', 'y', 'z']].values.tolist()
    #     spline = cq.Workplane("YZ").spline(lline).toPending().close()
    #     splines.append(spline)
    #     llines.append(lline)
    #     show_object(spline, name="Points", options={"opacity": 1})



    # point_size = 0.1
    # wp = cq.Workplane("YZ")
    # for i, row in df.iterrows():
    #     print(i, end="\r")
    #     if i > 100:
    #         break
    #     x, y, z = row['x'], row['y'], row['z']
        # wp = wp.union(cq.Workplane("YZ").transformed(offset=(x, y, z)).sphere(point_size))
        # wp = wp.sphere(point_size).translate((x, y, z))

    # show_object(wp, name="Point Cloud2", options={"opacity": 0.5})

    ### Known Issues:
    # Crosssectional area does not match the APC propeller geometry file. For details, use APC_comparisons(), comparisons_plot() in Blade.py
    '''Possible causes include: 
    different airfoil coordinates (APC12), different transition methods, extrapolation from sparcely defined airfoils (E63),  
    different maximum airfoil thicknesses (e.g.: thickness measured 90° to chord, or 90° to chamber - see "thickness_mode"
    in Airfoil_Section.py)'''

    # APC does not provide their exact airfoils. They claim APC12 = NACA12, but also state the following on their website:
    '''The dominant basis for the primary airfoil shape used in most APC propellers is similar to the NACA 4412 and Clark-Y 
    airfoils, except the leading edge is somewhat lower. Also, the aft region is somewhat thicker. This alters the zero-lift 
    angle by approximately one degree and provides greater lift without having to twist the blade more. Most blades have 
    some washout near the tip. For applications where Mach number effects become significant near the tip, either pitch 
    washout or camber reduction are used to minimize Mach drag rise.'''# www.apcprop.com/technical-information/engineering/

    # Transitions between airfoils are handled by interpolated y-coordinate of the airfoils at the same x-coord. The
    # individual airfoils are scaled (to max_thickness) before interpolation.
    # APC does not provide their exact transition method and only writes the following:
    '''Capability exists to smoothly "splice" together widely different airfoil shapes.'''

    ### Interpretations from Data-Files:
    # last airfoil is shifted in X and Y to match trailing edge of second last airfoil (by 90%). This is an arbitrary, but
    # necessary shift to avoid implausible edges to the radius-axis, as would be the case in some data-files.

    # Transition part is simple loft between last airfoil and ellipse at hub center. However, products have better transition.
    '''Cross-section geometry in and near the hub region is defined with specialized algorithms. The aerodynamic-dominant 
    airfoil must smoothly transition into a structural-dominant shape in a manner that emphasizes strength consistent with 
    milling machine tool constraints. '''

    # Transition part is sometimes exceeding the upper hub surface, which is not observed on products. -> Ellipse is shifted in Z (-thickness*0.05) to avoid this.

    # Transition includes a second hub_edge, which is a copy of the first hub_edge with a small offset in X for a more
    # consistent loft. This has been implemented to more resemble to the product but is not part of the manual.

    # Propeller has chamfers at the hub. This is not implemented

    ### Potential Issues:
    # Loft shapes can sometimes (strongly) change after unions...? (encountered during testing phase)
    # Export Filesize is large (~50-70MB). This is likely due to the high number of faces in the lofts. This can be reduced
    # by reducing the number of interpolation points. However, this will also reduce the quality of the propeller.

    return None

#generateSTL("5x3-PERF", r"C:\Users\jonas\OneDrive\ETH\FS2026\Semester Project\GITHUB\Repository\sim-pipeline", r"C:\Users\jonas\Downloads\New folder", 70)